### ISSUE TITLE
Static getter in a class results in SyntaxError with esm 3.2.23

### ISSUE THREAD

**Issue by Tronil** [standard-things/esm#804] opened 2019-05-16 08:46 UTC
The following can no longer be loaded with the 3.2.23 release:
```
export class Foo
{
    static get bar()
    {
        return "Foo";
    }
}
```
If you try you get:
```
static get bar()
               ^

SyntaxError: Invalid or unexpected token
    at Object.Module._extensions..js (module.js:664:10)
```
It works with 3.2.22.

**Comment by PazzaVlad** [comment] 2019-05-16 11:21
Have the same problem

**Comment by ptb** [comment] 2019-05-16 11:40
I'm having a similar issue, works with 3.2.22 but not 3.2.23:

```
node_modules/puppeteer/lib/Page.js:44
    static async create(client, target, ignoreHTTPSErrors, defaultViewport, screenshotTaskQueue) {
                 ^

  SyntaxError: Invalid or unexpected token
```

**Comment by jdalton** [comment] 2019-05-16 13:24
Yep, super sorry about that folks. Updated parsing support and missed smth. Will have it fixed in the next few hours.

**Comment by dnalborczyk** [comment] 2019-05-16 13:24
thanks guys for taking the time to report! looks like a regression.

@jdalton the following fail with `v3.2.3.`:
```
class Foo {
  static get bar() {}
  static set bar(val) {}
  static async afunc() {}
  static *gfunc() {}
  static async *agfunc() {}
}
```

**Comment by dnalborczyk** [comment] 2019-05-16 13:27
@jdalton uups, same time. 😄   btw, not sure if you noticed. the git release tags are tagged as `3.2.33` as supposed to `3.2.23`.

**Closed** 2019-05-16 15:01 UTC
Labels: bug

**Comment by jdalton** [comment] 2019-05-16 17:34
`esm` [v3.2.24](https://github.com/standard-things/esm/releases/tag/3.2.24) is released 🎉

**Comment by exogen** [comment] 2019-05-16 18:09
Thanks for the fix @jdalton! I'm noticing some cases are still having trouble however.

```console
$ node -r esm
> require('node-fetch')
/Users/brian.beck/Projects/node_modules/node-fetch/lib/index.js:899
	[Symbol.iterator]() {
                  ^

SyntaxError: Invalid or unexpected token
```

(that `[Symbol.iterator]()` method is on a class)

works fine on `3.2.22` and without `esm`!

**Comment by jdalton** [comment] 2019-05-16 18:10
I'll throw that into the test mix too : )

**Comment by andrewgremlich** [comment] 2019-05-16 19:12
Ditto to @exogen comment with the same error.
