### ISSUE TITLE
3.2.23 and 3.2.24 broken

### ISSUE THREAD

**Issue by steida** [standard-things/esm#807] opened 2019-05-16 19:32 UTC
Now sure why yet, but 3.2.22 works.

Investigating...

**Comment by dnalborczyk** [comment] 2019-05-16 21:33
hey @steida  before you digg too deep, it's likely a duplicate of: https://github.com/standard-things/esm/issues/803 https://github.com/standard-things/esm/issues/804

**Comment by djMax** [comment] 2019-05-16 22:38
This is very much still broken, and 803 and 804 claim it as closed.

**Comment by dnalborczyk** [comment] 2019-05-16 22:42
@djMax    there still seems to be a "leftover" regression regarding `computed property names`.

**Comment by djMax** [comment] 2019-05-16 22:43
I would consider unpublishing 23 and 24.

**Comment by tomlinton** [comment] 2019-05-17 00:32
Same experience with broken computed property names.

**Comment by dnalborczyk** [comment] 2019-05-17 00:43
@jdalton  repro:

```js
class Foo {
  ["bar"]() {}  // not working
}

```

_marking as "new" bug, since it was mentioned in the other [closed] thread._

**Comment by gr2m** [comment] 2019-05-17 04:29
I just run into the same problem, here is my minimal test case: https://github.com/gr2m/esm-bug

```js
// index.js
require = require("esm")(module/*, options*/)

const { MyClass }= require("./module.js")
const mc = new MyClass()
mc[Symbol.iterator]()

// module.js
export class MyClass {
 [Symbol.iterator]() {
   console.log('test')
 }
}
```

**Closed** 2019-05-17 05:16 UTC
Labels: bug

**Comment by jdalton** [comment] 2019-05-17 05:27
`esm` [v3.2.25](https://github.com/standard-things/esm/releases/tag/3.2.25) is released :tada:

**Comment by gr2m** [comment] 2019-05-17 05:30
That fixed it for me, cheers 👍

**Comment by steida** [comment] 2019-05-17 13:22
Fixed here as well. Thank you!
