### ISSUE TITLE
Load file(s) outside package as ESM

### ISSUE THREAD

**Issue by mAAdhaTTah** [standard-things/esm#77] opened 2017-08-29 12:44 UTC
Use case: Building a CLI tool where I'd like the rc file to be ESM.

Because `@std/esm`'s behavior is to scope the loader to just the package, I get `unexpected token import` when `require()` / `import()` 'ing the file. Is there any way to mark that this file should be parsed as ESM?

**Comment by jdalton** [comment] 2017-08-29 14:21
Hi @mAAdhaTTah!

There isn't at the moment. I'm open to API suggestions or heuristics to enable it. What I want to avoid is accidentally stepping on packages toes in production. So if there's a way to cater to CLIs without stepping on prod deps that would rock 🤘

**Comment by jdalton** [comment] 2017-08-29 15:05
> Alternatively, possible to readFile and pass the contents a @std/esm API to compile it ourselves?

That could work! I'll kick it around ⚽️

**Comment by mAAdhaTTah** [comment] 2017-08-29 15:16
Cool. Happy to beta test an API if you get something working.

**Comment by jdalton** [comment] 2017-08-29 16:33
The more I'm thinking about it.... since we've changed the in-file API to be a loader factory. You're opting-in by using the produced loader so we could make it so that
```js
const LoaderFactory = require("@std/esm")
const loaderA = LoaderFactory(module)
const loaderB = LoaderFactory(module, options)
```
This could allow custom options (different than those specified in your package.json) and since you're opting-in by using the produced loader I can remove the package guard per module loaded after.

**Comment by mAAdhaTTah** [comment] 2017-08-29 16:56
Yeah, that would work. Is it currently possible to opt-out of the package guard per-module now via package.json? Or that would have to be added as part of this proposal/API?

Also, if this is going to result in API changes, can we reopen the issue?

**Comment by bmeck** [comment] 2017-08-30 13:11
If no extensions are used, this seems doable. Otherwise people will need to start guarding against the extensions.

I would suggest adding a `package.json` if possible and extensions are needed.

**Comment by mAAdhaTTah** [comment] 2017-08-30 14:31
Can you clarify "extensions" in the above comment? File extensions or node extensions or...?

**Comment by bmeck** [comment] 2017-08-30 14:37
@mAAdhaTTah non-spec behavior. The [unlockables](https://github.com/standard-things/esm#unlockables)

**Comment by bahmutov** [comment] 2017-09-04 17:03
So there is no way to load `node_modules` ES modules at the moment? Like trying to load a `lodash-es` dependency.

```js
import property from 'lodash-es/property'
// { import baseProperty from './_baseProperty.js';
// SyntaxError: Unexpected token import
```
The local files are working

**Comment by jdalton** [comment] 2017-09-04 18:02
> So there is no way to load `node_modules` ES modules at the moment?

Not without the requesting package opting-in. This issue will enable it though through an options param. It's already committed in the master branch btw.

**Comment by bahmutov** [comment] 2017-09-04 18:10
Cool, thanks @jdalton I will be watching this thread, maybe soon my dream of rolling into smallest possible bundles will come true! Then I will *build* my library and roll in all dependencies to have 0 production deps.

**Comment by Jamesernator** [comment] 2017-09-06 00:23
I couldn't find any packages that are distributed as `.mjs` to verify, but if `lodash-es` were distributed as `.mjs` instead of `.js` then the [above example](https://github.com/standard-things/esm/issues/77#issuecomment-327002827) would just work right? and that the issue is just that you can't configure `@std/esm` extras for other packages currently.

**Comment by jdalton** [comment] 2017-09-06 04:31
Closed by https://github.com/standard-things/esm/commit/4486fdba7067e502dc92dab78552e8c2551394b6, https://github.com/standard-things/esm/commit/7b7e81c58b971307609aa930ec03a349fae44723, https://github.com/standard-things/esm/commit/3eac8b4859d12a108d38811dd20ec3a61cc150df, https://github.com/standard-things/esm/commit/748c8937d880bd116106f797370063e9832b2b8f, https://github.com/standard-things/esm/commit/346dec103a74e24b4cad60e105d771d67d8b1497.

**Closed by jdalton** 2017-09-06 04:31 UTC
Labels: enhancement

**Comment by jdalton** [comment] 2017-09-07 15:08
v0.8.0 is [released](https://github.com/standard-things/esm/releases/tag/0.8.0).
