### ISSUE TITLE
Cannot override config files when used programmatically

### ISSUE THREAD

**Issue by novemberborn** [standard-things/esm#501] opened 2018-07-12 16:42 UTC
See https://github.com/avajs/ava/issues/1820#issuecomment-403250289. The user has a project with both AVA (`@next`) and `esm` installed. If `package.json` includes `{"esm": {mode: "strict"}}` then AVA fails to load the `ava.config.js` file.

AVA sets the mode to `"all"` when instantiating `esm`, but it seems like the `package.json` configuration still overrides the mode? Reproduced with v3.0.69.

**Comment by jdalton** [comment] 2018-07-13 15:39
Hi @novemberborn!

Thanks for the heads up. This is kind-of by design, but I think we can work on it. When passing options programmatically to `esm` the loader is using those options as the defaults but still allows users to provide their own options this is because folders or sub packages may want to be customized beyond the default options.

In this case though this is an entry script so it would seem reasonable that you'd want your options provided to the loader to at least apply to the entry script itself (regardless of subsequent module loads from the entry).

**Comment by novemberborn** [comment] 2018-07-13 15:44
> this is an entry script so it would seem reasonable that you'd want your options provided to the loader to at least apply to the entry script itself (regardless of subsequent module loads from the entry).

Yes that sounds correct, and is what I had assumed the behavior would be. Perhaps an `extend: false` option (name notwithstanding) could do the trick?

**Comment by jdalton** [comment] 2018-07-13 15:51
> Perhaps an extend: false option (name notwithstanding) could do the trick?

I'll try to make this just-work without adding extra config. My current plan is to use the programmatic options as the defaults for all non-entry scripts and use them as an override for the entry script.

**Comment by novemberborn** [comment] 2018-07-13 15:52
That would be a breaking change, no?

**Comment by jdalton** [comment] 2018-07-13 15:58
In the gradient scale of changes I think this would primarily effect folks in AVA's boat. So a test, bundle, or other util that uses `esm` to load configs). This change is likely something the user would expect to work already (just as you assumed). So from that standpoint it can be seen more as a bug fix, certainly something that I wouldn't mind patch or minor bumping for.

**Comment by jdalton** [comment] 2018-07-13 18:14
**Update:**

Thinking on this more. This would fundamentally change how `esm` handles options. At the moment we handle it in a per package way. A "package", as seen by `esm`, is any folder with options (specified in a variety of ways). Using the  programmatic `options` via AVA it sets the loader up with defaults. But then the file it loads can be anywhere. In this case it's in the user's project directory to load a config file. The user specifies a different set or rules for loading files which exclude ESM in `.js` so in this case we're respecting the user's config wishes. I think the better approach is to go the `--config-file` route at https://github.com/avajs/ava/issues/1857.

*Note:*

*Hi @cantremember 👋,*

*Node core and Node Module WG member here (me). 
The `.mjs` extension is still very experimental so you'll likely continue to run into rough edges with its use. The `esm` loader locks `.mjs` use down because we don't know what full support looks like just yet _(as it's still being ironed out in Node)_. There are several possible implementation routes for Node to take, many are not compatible with `--experimental-modules` today. This means there's a possibility that the code you write today for `--experimental-modules` will break in the future as things shake out. It's not a bad idea to avoid relying on experimental features for any production code.*

**Comment by novemberborn** [comment] 2018-07-13 19:48
@jdalton that's a pity. I'm not sure we can use `esm` if we then have to add a disclaimer about what happens when users have configured it in their project.

Config loading also happens early enough that we don't have a way for users to indicate they want to use `esm` to load an `.mjs` file, and I don't really want AVA to commit to loading `.mjs` *config* files if it doesn't handle `.mjs` test files.

Is your concern that any imports of the `ava.config.js` file should be loaded according to the user's settings?

Given that we're using the programmatic API, is there any hook where we can use `esm` to transpile the config file according to our own settings, so that we can then execute it ourselves through the `vm` module? The output code could then use the user's settings for any further imports.

**Comment by jdalton** [comment] 2018-07-13 21:23
I think going down the `extend: false` (whatever its named) would be the approach to take then since we can't reasonably detect intent here.

**Comment by novemberborn** [comment] 2018-07-13 21:41
Thanks!

How would that impact imports from the file itself?

**Comment by jdalton** [comment] 2018-07-13 21:52
For that loader instance I would simply disable resolving `esm` options so it would stick with the defaults provided by the programmatic API. So loading in the file itself would be dictated by whatever the programmatic options were.

**Comment by jdalton** [comment] 2018-07-13 23:55
**Update:**

I have this working locally. Bikeshed option names? I currently have `configurable` as the option but I'm open to others. It should express toggling respecting user provided options. Maybe `fixed` or `immutable` or `locked` or `force`.

**Closed** 2018-07-14 01:17 UTC
Labels: enhancement

**Comment by cantremember** [comment] 2018-07-14 03:04
@novemberborn thank you for bringing this issue over into `esm` 👍 

@jdalton i completely understand -- '.mjs' is experimental.  it just happens to be the most practical way to identify that a particular script is ESM-flavored.  it makes a lot of sense for an evolving adoption process.  i **deeply appreciate** that a project like `esm` is out there in the wild to enable folks like me to begin that process without a transpilation step.

i *could have* (a) turned off `strict` if i had needed to.  but keeping it on serves me much better than (b) being a Purist about how i express my `ava` config.  package.json gave me a backup plan, and i was able to stay `strict`.  my https://github.com/avajs/ava/issues/1820#issuecomment-403250289 was my observation that their CLIs doesn't allow the user to specify a config filename which would have allowed me to a be a Purist (a habit i'm trying to break)

💯

**Comment by novemberborn** [comment] 2018-07-14 12:14
@jdalton great! This works insofar as that AVA can load `ava.config.js` even if the project uses `mode: 'strict'`, but the project settings do not apply to imports *from* the `ava.config.js` file, at least as far as `mode: 'strict'` is concerned. I do seem to be able to import CJS modules despite AVA setting `cjs: false` so maybe this is just a `mode` issue?

**Comment by jdalton** [comment] 2018-07-14 17:30
Strict mode allows importing CJS files. They currently are handled as `--experimental-modules` handles them, as a single `default` export _(no named exports support)_. Strict means that only `.mjs`.
