### ISSUE TITLE
reported bug at node repository: std/esm > 0.16.0 with node --inspect flag

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#178] opened 2017-12-06 14:49 UTC
Hey John, just saw this over at the _node_ repository:

https://github.com/nodejs/node/issues/17485

**Comment by jdalton** [comment] 2017-12-06 15:18
Thanks for the heads up @dnalborczyk!

@motss
Can you create a simple repro repo for me to look at?
I was just thinking about inspect and how to add a scenario test for it.

**Comment by jdalton** [comment] 2017-12-06 15:40
@motss FWIW the master branch is working for me on Node 8 and 9. With a simple test. Having a repro repo would help narrow down the cause.

**Comment by motss** [comment] 2017-12-06 16:06
@jdalton I just created a repo and it's surprising enough to find out that it does not work for Node 9.2.0 on my Windows 10 machine. Will check it out on my Macbook tomorrow.

Here's the link: https://github.com/motss/test-esm

Hope this helps for debugging.

**Comment by motss** [comment] 2017-12-06 16:08
Here's how to run the app.

```sh
# NPM install
$ npm i

# Build and run
$ npm run build && npm run debug
```

**Comment by jdalton** [comment] 2017-12-06 16:25
Thanks @dnalborczyk!

I'm getting this on macOS. It looks to be working after a string of debug inspector logs *(I can load each up)*

![](https://user-images.githubusercontent.com/4303/33672252-a3996266-da5e-11e7-91b2-e39889f75277.png)

**Comment by jdalton** [comment] 2017-12-06 16:36
I noticed if I have vscode insider build open it tries to hog the inspector port and Node complains. If I close vscode then node inspect works. Could this be what you're seeing.

**Comment by jdalton** [comment] 2017-12-06 19:29
Closing as `invalid` since I can't reproduce the issue. However, that doesn't mean it's set in stone. If more details are provided or there's something else to track then we'll get to the bottom of it.

**Closed** 2017-12-06 19:28 UTC
