### ISSUE TITLE
Cannot find module './lib/_stream_writable.js

### ISSUE THREAD

**Issue by clock157** [standard-things/esm#710] opened 2019-01-19 09:55 UTC
![image](https://user-images.githubusercontent.com/4002237/51425165-5a82f900-1c13-11e9-8cf8-eafb24892655.png)

![image](https://user-images.githubusercontent.com/4002237/51425141-0d9f2280-1c13-11e9-9fde-4e620b30e25a.png)

this problem maybe caused by update 3.1.0?

**Comment by dnalborczyk** [comment] 2019-01-19 14:00
hey @clock157  very likely a duplicate of https://github.com/standard-things/esm/issues/709

**Comment by jdalton** [comment] 2019-01-19 16:57
Hi @clock157!

As @dnalborczyk mentioned this looks like a duplication of #709. Once we release the v3.1.1 please revisit and see if the issue persists.

**Closed by jdalton** 2019-01-19 16:57 UTC
Labels: duplicate

**Comment by clock157** [comment] 2019-01-20 06:17
thank you guys, the issue has been fixed!
